name: UniversalPluginManager
main: com.minecraftserver.universalpluginmanager.UniversalPluginManager
website: http://www.minecraftserver.com/
version: 0.02 Alpha
author: M0P
commands:
   upm:
      description: Manage your Plugins
      
permissions:
    pvptoolkit.fly.invincible:
        description: Makes you invincible while flying
        default: op